name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      fail-fast: true
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install build and pack
        timeout-minutes: 5
        run: |
          pnpm install
          pnpm build
          pnpm pack
        env:
          CI: true
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tgz,./dist/*.min.js"
          token: ${{ secrets.GITHUB_TOKEN }}
